import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("onboarding", "routes/onboarding.tsx"),
  route("dashboard", "routes/dashboard.tsx"),
  route("sessions", "routes/sessions.tsx"),
  route("approvals", "routes/approvals.tsx"),
  route("audit", "routes/audit.tsx"),
  route("operators", "routes/operators.tsx"),
  route("lex", "routes/lex.tsx"),
  route("kinetic", "routes/kinetic.tsx"),
  route("finance", "routes/finance.tsx"),
  route("terminology", "routes/terminology.tsx"),
  route("reports", "routes/reports.tsx"),
  route("geopolitics", "routes/geopolitics.tsx"),
  route("immigration", "routes/immigration.tsx"),
  route("pricing", "routes/pricing.tsx"),
  route("entertainment", "routes/entertainment.tsx"),
  route("creativity", "routes/creativity.tsx"),
  route("api/ai/generate", "routes/api.ai.generate.tsx"),
  route("api/telegram/webhook", "routes/api.telegram.webhook.tsx"),
  route("api/discord/interactions", "routes/api.discord.interactions.tsx"),
  route("api/public/check", "routes/api.public.check.tsx"),
  route("api-keys", "routes/api-keys.tsx"),
  route("api-docs", "routes/api-docs.tsx"),
  route("referrals", "routes/referrals.tsx"),
  route("integrations", "routes/integrations.tsx"),
  route("for-law-firms", "routes/for-law-firms.tsx"),
  route("for-financial-services", "routes/for-financial-services.tsx"),
  route("roi-calculator", "routes/roi-calculator.tsx"),
  route("free-assessment", "routes/free-assessment.tsx"),
  route("marketing", "routes/marketing.tsx"),
] satisfies RouteConfig;
